ALTER TABLE users
    ADD COLUMN private_account BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hide_follower_count BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hide_following_count BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hide_follower_list BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hide_following_list BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hide_add_friend_button BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hide_follow_button BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hide_from_mutual_list BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN message_button_enabled BOOLEAN NOT NULL DEFAULT TRUE;
